# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_isoform_multithread <- function(gff3, genome_bam, isoform_gff3, tss_tes_stat, genomefa, transcript_fa, isoform_parameters, raw_splice_isoform) {
    invisible(.Call(`_FLAMES_find_isoform_multithread`, gff3, genome_bam, isoform_gff3, tss_tes_stat, genomefa, transcript_fa, isoform_parameters, raw_splice_isoform))
}

#' Rcpp port of flexiplex
#'
#' @description demultiplex reads with flexiplex, for detailed description, see
#' documentation for the original flexiplex: https://davidsongroup.github.io/flexiplex
#'
#' @param r_segments List defining the barcode structure
#' @param r_barcode_groups List defining barcode groups
#' @param reads_in Input FASTQ or FASTA file
#' @param reads_out output file for demultiplexed reads
#' @param stats_out output file for demultiplexed stats
#' @param bc_out WIP
#' @param reverseCompliment bool, whether to reverse complement the reads after demultiplexing
#' @param n_threads number of threads to be used during demultiplexing
#' @return integer return value. 0 represents normal return.
#' @export
flexiplex <- function(r_segments, r_barcode_groups, max_flank_editdistance, reads_in, reads_out, stats_out, bc_out, reverseCompliment, n_threads) {
    .Call(`_FLAMES_flexiplex`, r_segments, r_barcode_groups, max_flank_editdistance, reads_in, reads_out, stats_out, bc_out, reverseCompliment, n_threads)
}

variant_count_matrix <- function(bam_path, seqname, pos, indel, verbose) {
    .Call(`_FLAMES_variant_count_matrix`, bam_path, seqname, pos, indel, verbose)
}

